name: Push Docker Image

# Use action since Apps don't have access to Packages yet
# Plus it's good to see how Actions are slow because of Java instalation and no caching

on:
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Test
        run: ./gradlew test
      - name: Docker login
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Build and Deploy via Jib
        run: ./gradlew jib
