name: Push Docker Image

on:
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Test
        run: ./gradlew test
      - name: Build and Deploy via Jib
        run: ./gradlew jib
